/** Top 20 emplacements — types déjà sur le site Derra + terrain (Cynara). Pas dans l’ebook. */
export const TOP_SPOTS_TITLE = "Top 20 — Meilleurs emplacements";
export const TOP_SPOTS_SUBTITLE =
  "Café et snack. Types de spots déjà chez nous (chantiers, entreprises, tabacs, médicaux…) — pas des adresses clients. Tu juges, on n’a pas collé ça dans l’ebook.";

export type SpotFit = "Fort" | "Moyen" | "Faible";

export const TOP_SPOTS = [
  {
    rank: 1,
    name: "Chantier BTP",
    example: "Chez nous : Cynara / Rollier — récoltes en vidéo membre.",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Les gars restent, boivent et mangent toute la journée. Souvent le meilleur ticket café + snack.",
    who: "Contremaître ou chef de chantier.",
    trap: "Le chantier a une date de fin. Anticipe le déménagement de la machine.",
  },
  {
    rank: 2,
    name: "Atelier / site technique",
    example: "Menuiserie, métal, maintenance — déjà dans nos entreprises / sites industriels.",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Équipe fixe, pauses régulières, peu de cantine. Même logique que le chantier, plus stable.",
    who: "Patron ou responsable d’atelier.",
    trap: "Poussière et graisse : place la machine à l’abri, pas dans le flux des machines-outils.",
  },
  {
    rank: 3,
    name: "Entrepôt / logistique",
    example: "Sites type entreprise / industriel sur le site Derra.",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Équipes en rotation, faim et café à des heures bizarres. Le snack part fort.",
    who: "Responsable site ou facility.",
    trap: "Horaires 24/6 : vérifie qui voit la machine la nuit (vol snack).",
  },
  {
    rank: 4,
    name: "Entreprise sans cantine",
    example: "Bureaux Genève / Vernier — nos réalisations « point pause entreprise ».",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Du monde tous les jours, pas d’autre option. Café d’abord, snack si 14 jours de preuve.",
    who: "Gérant, RH ou facility manager.",
    trap: "S’ils ont déjà une cantine ou un Nespresso à gogo, le volume tombe.",
  },
  {
    rank: 5,
    name: "Site industriel",
    example: "Combo café & confiseries — déjà en galerie « entreprise ».",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Beaucoup de têtes, trois pauses. Haute capacité si le site est grand.",
    who: "Facility / direction de site.",
    trap: "Parfois un prestataire déjà en place. Note la date de fin de contrat.",
  },
  {
    rank: 6,
    name: "Open space / grande boîte",
    example: "Installations « open space » et « grande consommation » sur le site.",
    cafe: "Fort" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Café quasi sûr. Snack : seulement s’il n’y a pas déjà une micro-cuisine pleine.",
    who: "Office manager / facility.",
    trap: "Comité et délais. Tu vends le zéro frais, pas un projet IT de 6 mois.",
  },
  {
    rank: 7,
    name: "Garage / carrosserie",
    example: "Même famille que l’atelier — prospects entourage (ebook).",
    cafe: "Fort" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Équipe + clients qui attendent. Café très bon. Snack selon le nombre de mécanos.",
    who: "Patron.",
    trap: "Une petite équipe (3 personnes) = machine faible. Compte les têtes, pas la devanture.",
  },
  {
    rank: 8,
    name: "Centre médical / cabinet",
    example: "Déjà listé : centres médicaux, témoignage Carouge.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "Staff + salle d’attente. Café OK. Snack souvent trop sensible (hygiène, image).",
    who: "Médecin titulaire ou secrétariat.",
    trap: "Règles plus strictes. Café simple, pas un snack ouvert.",
  },
  {
    rank: 9,
    name: "Tabac & kiosque",
    example: "Meyrin / commerces partenaires — photos Necta & Saeco sur le site.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "Ils vendent déjà des snacks. Ton café en dépôt peut marcher. Ton snack les concurrence.",
    who: "Gérant du tabac.",
    trap: "Passage rapide ≠ tasses. S’ils ne poussent pas le café, ça dort.",
  },
  {
    rank: 10,
    name: "Barber / salon",
    example: "Cibles entourage dans l’ebook et les scripts.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "Clients qui attendent + équipe. Bon premier « oui ». Volume souvent moyen.",
    who: "Patron du salon.",
    trap: "Petit salon = 250 tasses. OK pour apprendre, pas pour rêver 800.",
  },
  {
    rank: 11,
    name: "Commerce avec attente",
    example: "Commerces / kiosques déjà en galerie.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "File, rendez-vous, réparation : les gens attendent, ils prennent un café.",
    who: "Gérant.",
    trap: "Commerce de passage (in-out 30 sec) = machine morte.",
  },
  {
    rank: 12,
    name: "Restaurant / cuisine (équipe)",
    example: "Prospects restos dans l’ebook — pour le staff, pas la salle.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "L’équipe veut un café hors service. La salle a déjà à boire.",
    who: "Patron ou chef.",
    trap: "Ils ont déjà des machines pro. Ton offre doit être plus simple et moins chère pour eux.",
  },
  {
    rank: 13,
    name: "Administration / bureau public",
    example: "Administrations — déjà sur la page clients.",
    cafe: "Moyen" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Du monde, horaires stables. Snack possible à la pause.",
    who: "Achats / facility / secrétariat général.",
    trap: "Appel d’offres, lenteur. Pas ton 1er spot.",
  },
  {
    rank: 14,
    name: "Salle de sport",
    example: "Salles de sport — déjà dans nos types de clients.",
    cafe: "Faible" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Café souvent faible (les gens veulent de l’eau). Snack / boisson : mieux, si ça ne vole pas.",
    who: "Gérant de salle.",
    trap: "Vestiaires = vol. Pose sous les yeux de l’accueil.",
  },
  {
    rank: 15,
    name: "Association / club",
    example: "Associations — déjà listées sur le site.",
    cafe: "Moyen" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Matchs, répétitions, permanences : des pics, pas un flux lundi–vendredi.",
    who: "Président ou trésorier.",
    trap: "Creux en semaine. Calcule sur le mois, pas sur le samedi soir.",
  },
  {
    rank: 16,
    name: "Showroom / concession",
    example: "Réalisations « showroom » entreprise.",
    cafe: "Moyen" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "Accueil clients + vendeurs. Café image. Snack rarement utile.",
    who: "Directeur de site.",
    trap: "Ils veulent du beau, pas du volume. Occase trop moche = non.",
  },
  {
    rank: 17,
    name: "Hôtel (personnel)",
    example: "Pas en vitrine, mais même logique « équipe qui reste ».",
    cafe: "Moyen" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Le staff de nuit / ménage a besoin d’un point café-snack hors bar.",
    who: "Gouvernante ou directeur.",
    trap: "Le bar de l’hôtel te voit comme un concurrent. Vise les coulisses, pas le lobby.",
  },
  {
    rank: 18,
    name: "École / campus",
    example: "Cité dans les Q/R : possible, plus lent.",
    cafe: "Moyen" as SpotFit,
    snack: "Moyen" as SpotFit,
    why: "Du monde, mais paperasse, prestataire, règles.",
    who: "Direction / intendance.",
    trap: "Pas un 1er spot. Reviens quand tu as un parc et un vrai dossier.",
  },
  {
    rank: 19,
    name: "Petit commerce de passage",
    example: "Commerces « in-out » — on les a, ça ne tire pas toujours.",
    cafe: "Faible" as SpotFit,
    snack: "Faible" as SpotFit,
    why: "Facile à signer (un proche). Mauvais pour les chiffres.",
    who: "Commerçant.",
    trap: "250 tasses max souvent. OK pour tester, tu déplaces si ça ne part pas en 14 jours.",
  },
  {
    rank: 20,
    name: "2e machine snack sur un spot café déjà prouvé",
    example: "Le vrai plus snack du pack — pas un nouveau type de lieu.",
    cafe: "Fort" as SpotFit,
    snack: "Fort" as SpotFit,
    why: "Le décideur te connaît, le passage est mesuré. C’est là que le snack encaisse.",
    who: "Le même hôte que le café.",
    trap: "Ajouter un snack sur un café mort = deux machines qui dorment.",
  },
] as const;

export const TOP_SPOTS_RULES = [
  "Les gens restent (chantier, atelier, bureau). Ils ne font pas que passer.",
  "Quelqu’un décide en face de toi — pas un appel d’offres de 8 mois pour ta 1re machine.",
  "Café d’abord. Snack ensuite, sur un spot qui a déjà 14 jours de vrais chiffres.",
  "Un type de spot « Fort » mal placé (3 personnes, pas de prise) reste faible.",
];
